[package]
name = "chakkar"
version = "0.1.0"
edition = "2021"
authors = ["Supreet Sethi <supreet.sethi@gmail.com>"]

[dependencies]
png = "0.17"
clap = "4.0"
log = "0.4"
env_logger = "0.10"
rayon = "1.7"


[dev-dependencies]
assert_fs = "1.0"
